### ISSUE TITLE
mqtt: SERVER: The connection was closed because MQTT keep-alive check failed.

### ISSUE THREAD

**Issue by agronc** [Leverege/microchip-avr-iot#11]
GCP IoT Core showing error: mqtt: SERVER: The connection was closed because MQTT keep-alive check failed." Error Message: [link] https://imgur.com/2Aragbp

Under the monitoring tab, I can see data sent/received, however I believe the above error is preventing the data being sent to firebase.

Have tried rebuilding the avr-iot device, which indicate data is being sent with no errors.

Is there a specific reason why I might be getting this error?
@mattgif @Yitaek @ericsibored @alvarowolfx

**Comment by mattgif** [comment]
There's an error getting your data through IoT Core. Is this an out-of-the-box device, or have you modified the payload or settings beyond those listed in the setup guide?

Possible issues include:

- MQTT payload too large
- Registry region / device region mismatch (the setup assumes US-CENTRAL1)
- Billing not enabled in GCP

**Comment by agronc** [comment]
thanks for the reply @mattgif ,
I haven't made any modifications to the device, only followed the setup guide. A couple of months ago, when I initially tried the guide it worked perfectly.

For payload size, are you referring to this item?

#define TOPIC_SIZE 100      // Defines the topic length that is supported when we process a published packet
#define PAYLOAD_SIZE 200       // Defines the payload size that is supported when we process a published packet
#define NUM_TOPICS_SUBSCRIBE 1 // Defines number of topics which can be subscribed

I've checked under the GCP project, I can see its under US-CENTRAL1.

I've also upgraded billing to the blaze version.

I should note that the device works as I can connect it to the microchip default https://avr-iot.com/device/{device ID}, obviously thats before I started following the guide etc.

I also tried creating a new project and following the guide again, with no luck unfortunately. 
Your help would be appreciated :)

**Comment by aaronburnie** [comment]
I was having the same issue but managed to fix it by deleting all pub/sub configurations and IoT Core Registries and began again. I also copied and pasted the device pub key instead of uploading it. Likely this didn't actually do anything though.
I am using:
Registry ID: AVR-IOT
Project ID: Something that I specified
Location: us-central1
within header IoT_Sensor_Node_Config.h the configuration must match what is setup in your GCL.

#define CFG_PROJECT_ID "your_project"
#define CFG_PROJECT_REGION "us-central1"
#define CFG_REGISTRY_ID "AVR-IOT"
#define CFG_MQTT_HOST "mqtt.googleapis.com"

**Comment by agronc** [comment]
Still no luck, here is what I have tried so far:

Delete existing registries, projects etc - Started from scratch.

Followed the guide;
lights are: blue (ON all the time), green (ON all the time) and yellow blinking.

I also checked the Config.h to make sure it contains same info as the ones provided.

Checked to make sure region is us-central1 and other details match.

it seems that the realtime database within the firebase project has not been created (Billing has been upgraded to Blaze).

Only error that popped up during script installation were;
`i  deploying functions
Error: There was an error reading ./functions/package.json:
 Engines field is required but was not found in ./functions/package.json.
To fix this, add the following lines to your package.json:
      "engines": {
        "node": "8"
      }`

also this issue came up, not sure if it would affect the outcome;

`found 2 vulnerabilities (1 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Creating a production build of the UI (this may take a few minutes)...

> microchip-ui@2.0.0 build /home/my_dir/microchip-avr-iot/setup/ui
> webpack --progress --config webpack.config.prod.js

Failed to load ./.env.
Hash: c5cb8acdca35f21537d8                                                          
Version: webpack 4.31.0
Time: 103140ms
Built at: 07/06/2019 3:41:21 AM`

Not sure if there's anything else I can try at this point, hopefully its something trivial

**Comment by Moji14** [comment]
Hello guys,
I hope this help you...
Node.js 6 has deprecated you need to update your code.

Regards

**Comment by agronc** [comment]
> Hello guys,
> I hope this help you...
> Node.js 6 has deprecated you need to update your code.
> 
> Regards

I've tried something similar to that with no luck.

**Comment by mattgif** [comment]
I haven't been able to reproduce this error on my end. I pushed up a version with the Node 8 update and other dependency updates. Can you scrap the repo from your cloud shell, remove the existing cloud functions, and try it fresh from the new build?

**Comment by agronc** [comment]
> I haven't been able to reproduce this error on my end. I pushed up a version with the Node 8 update and other dependency updates. Can you scrap the repo from your cloud shell, remove the existing cloud functions, and try it fresh from the new build?

Hey Mat,
tested it again, works perfectly, it seems that the node + functions dependency update was preventing it from working. thanks

**Comment by mattgif** [comment]
Phew! Glad to hear it.
