### ISSUE TITLE
Use "open in cloud shell" feature

### ISSUE THREAD

**Issue by ptone** [Leverege/microchip-avr-iot#3]
we can auto clone the repo in the users cloud-shell directly from the repo readme:

https://cloud.google.com/shell/docs/open-in-cloud-shell

**Comment by mattgif** [comment]
We tried that initially, but ran into a few problems:

- It didn't launch in a specified project, so the startup script doesn't have access to project level variables
- The shell itself would hang or crash on the provisioning step pretty regularly
- When trying to integrate "open in cloud shell" with a tutorial, the tutorial would open the markdown file editor bigger than the tutorial and shell, which was confusing.

If there are some recent updates or work-arounds, we can definitely revisit.
