### ISSUE TITLE
Executing setup.sh script

### ISSUE THREAD

**Issue by jpiwek** [Leverege/microchip-avr-iot#4]
After invoking setup.sh in Google Cloud Shell I get many errors  and nothing is set up no project, registry, device, pub/sub, device entries.... 

Do you have a description to do all this setup manually?

Best,
Janus

**Comment by mattgif** [comment]
Are you running the setup.sh script in your GCP project's shell? 

Double check that you configured the project and cloned in to the shell as outlined in steps 1 (Set up your GCP and Firebase Projects) and 2 (Clone this repo in Cloud shell) of this repo's [README](https://github.com/Leverege/microchip-avr-iot/blob/master/README.md).

**Comment by jpiwek** [comment]
It seems like this line 

>  "analyze": "plato -r -d report -e .eslintrc src",
in > ui\package.json
fails.... I deleted the comma and then the build worked !

**Comment by jpiwek** [comment]
Is it also possible to use cloud functions triggered by pubsub to store data in Big Query?

**Comment by mattgif** [comment]
Thanks for the catch on the invalid JSON! Fix published.

Re: Cloud functions / Big Query: Definitely. Using the [Big Query Node.js client library](https://github.com/googleapis/nodejs-bigquery), you could create a function analogous to this library's `recordMessage` function.
