### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by teransantiago** [Leverege/microchip-avr-iot#9]
Hello,
I have been trying to use this excellent guide, but the board is connecting to the wifi(I supposed it because the blue led is going on, but then the red is on and I cannot see anything in the firebase provided address, just the points trying to charge information ). 
There are a couple of things that I have not clear, and they may be the cause of this problem. (excuse me for this silly questions)
1)part "Run the Quickstart Script". step 4. Does the last portion of the url include the "/" symbol?
2)part "Update your AVR-IoT device firmware". step 5. Corresponds the "GCP Project ID" field to the "Project ID" field in the GCP ? and corresponds the "Registry ID" field to the "Project Number" field in the GCP? 
For this last question, there are 3 fields in GCP (Project name, project ID and Project number), and I have changed them in the AVR program to check if this is the mistake, but the firebase doesn't receive the information from the board.

One condition that seems strange to me is that in firebase my user is "pay as you go", but in GCP I have less than 300 euros as part of the free account. I don't know if this may cause a problem in this sample.

I'll thank you a lot for your response.

Best Regards.

**Comment by Moji14** [comment]
Hi teresantiago,
The connection process of the AVR IoT development board
1 All the LEDs blink 2 times in a sequence.
2 If all WiFi credentials are ok the BLUE LED will be fixed on
3 The IoT board will connect to the cloud system and switch on the GREEN LED
4 If the cloud connection is successful then will start sendind data using que JSON line and sblinking the YELLOW LED

It looks that your stack on somewhre in between steps 1 and 2.
If I were you, I'll check WiFi credentials first of all. I also recommend you have a look on the AVR IoT user manual.
http://ww1.microchip.com/downloads/en/DeviceDoc/AVR-IoT-WG-Development-Board-User-Guide-50002809B.pdf 

All of the AVR IoT development board here:

https://www.microchip.com/DevelopmentTools/ProductDetails/AC164160
